saalfeldlab/paintera

src/main/java/bdv/fx/viewer/BufferExposingWritableImage.java
src/main/java/bdv/fx/viewer/ByteArrayAccessARGB.java
src/main/java/bdv/fx/viewer/ByteBufferAccessARGB.java
src/main/java/bdv/fx/viewer/CanvasPane.java
src/main/java/bdv/fx/viewer/ImageOverlayRendererFX.java
src/main/java/bdv/fx/viewer/InteractiveDisplayPaneComponent.java
src/main/java/bdv/fx/viewer/MultiResolutionRendererFX.java
src/main/java/bdv/fx/viewer/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/SimpleInterruptibleProjectorPreMultiply.java
src/main/java/bdv/fx/viewer/TransformAwareBufferedImageOverlayRendererFX.java
src/main/java/bdv/fx/viewer/VolatileHierarchyProjectorPreMultiply.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/composition/CompositeProjectorPreMultiply.java

Write into `WritableImage` directly to avoid [image copies for every single (!) rendering](https://github.com/saalfeldlab/paintera/blob/master/src/main/java/bdv/fx/viewer/TransformAwareBufferedImageOverlayRendererFX.java#L111-L115).

Merge multiscale painting avoid image copies branch

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshInfo.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshInfoNode.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshPane.java

Add option to enable individual per-mesh controls
Fixes #18

Add global mesh settings controls

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/config/CoordinateConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/control/navigation/OrthogonalCrossSectionsIntersect.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceDeserializer.java

Add UI for centering ortho slices at arbitrary position

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/control/IdSelector.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Selection.java
src/main/java/org/janelia/saalfeldlab/paintera/control/lock/LockedSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/control/lock/LockedSegmentsOnlyLocal.java
src/main/java/org/janelia/saalfeldlab/paintera/control/lock/LockedSegmentsState.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/AbstractHighlightingARGBStream.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/AbstractSaturatedHighlightingARGBStream.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/GoldenAngleSaturatedHighlightingARGBStream.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/HideLockedSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/HighlightingStreamConverter.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/ModalGoldenAngleSaturatedHighlightingARGBStream.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/converter/HighlightingStreamConverterNode.java

Fixes #35 
For now, do not lock marked segments (future work)

Mark segments complete

---

src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentOnlyLocal.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceSerializer.java

Forget canvas on exit

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGenerator.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignment.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java

Fixes #56 
- Make root group non mutable in MeshGenerator
- Add isEnabled state instaed
- fix synchronization in MeshGenerator

Address #56 (zombie meshes)

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java

Pass the correct supplier

---

src/main/java/org/janelia/saalfeldlab/paintera/N5Helpers.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/SaveOnExitDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/control/CommitChanges.java
src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentOnlyLocal.java
src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentState.java
src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/UnableToPersist.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/GenericBackendDialogN5.java

Throw on assignment persist fail

---

src/main/java/org/janelia/saalfeldlab/paintera/LockFile.java
src/main/java/org/janelia/saalfeldlab/paintera/LockFileAlreadyExistsDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java

Add lock file

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGenerator.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGeneratorJobManager.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/cache/BlocksForLabelDelegate.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java

Mesh deadlock part2

---

.gitignore
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGenerator.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshInfo.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshSettings.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/config/MeshSettingsSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshInfoNode.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshPane.java

Can be useful for comparing two different segmentations

Inflate meshes

---

src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/config/Viewer3DConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/Viewer3DConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManager.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java
src/main/java/org/janelia/saalfeldlab/paintera/state/IntersectingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/Viewer3DFX.java

When you don't want to allocate resources for generating and showing 3D, disable it.

Disable 3d

---

src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java

Still issue (probably race condition) with invalid mask generation/state

Disable click paint

---

src/main/java/bdv/fx/viewer/BufferExposingWritableImage.java

This is closer to what we intend to do, came up on our [gitter channel](https://gitter.im/saalfeldlab/general?at=5b2862b42b706312a6596261)

Use Class.getDeclaredMethod instead of Class.getDeclaredMethods

---

src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentState.java

Use applyImpl to avoid duplication of actions

---

src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentOnlyLocal.java

Only check for assignment equality if from is assigned to segment already

---

src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateSerializer.java

Reduce footprint of mesh settings in project file.

Store settings only for active meshes

---

pom.xml

Made the necessary changes to comply with [pom-scijava-base](https://github.com/scijava/pom-scijava-base) re-enable the maven enforcer.

Do not skip enforcer

---

README.md
pom.xml
src/main/java/org/janelia/saalfeldlab/fx/ui/DirectoryField.java
src/main/java/org/janelia/saalfeldlab/fx/ui/Exceptions.java
src/main/java/org/janelia/saalfeldlab/fx/ui/NamedNode.java
src/main/java/org/janelia/saalfeldlab/fx/ui/NumberField.java
src/main/java/org/janelia/saalfeldlab/fx/ui/ObjectField.java
src/main/java/org/janelia/saalfeldlab/fx/ui/SpatialField.java
src/main/java/org/janelia/saalfeldlab/paintera/N5Helpers.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDataset.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDatasetHandler.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/MipMapLevel.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/VolatileHelpers.java

`ctrl shift N` let's users create new label datasets.
Fixes #122 
Currently, 3D representations do not work yet. Merge, once fixed.

Create new label dataset through Paintera UI

---

src/main/java/org/janelia/saalfeldlab/fx/Labels.java
src/main/java/org/janelia/saalfeldlab/fx/TitledPanes.java
src/main/java/org/janelia/saalfeldlab/fx/undo/UndoFromEvents.java
src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentOnlyLocal.java
src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentStateWithActionTracker.java
src/main/java/org/janelia/saalfeldlab/paintera/control/undo/HasHistory.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/FragmentSegmentAssignmentOnlyLocalSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/BindUnbindAndNodeSupplier.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/StatePane.java

Fixes #125 
Need to use a little more to make sure everything works as intended before merge.

Undo for assignment actions

---

src/main/java/bdv/fx/viewer/MultiResolutionRendererFX.java
src/main/java/bdv/fx/viewer/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/PainterThread.java
src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/org/janelia/saalfeldlab/fx/ortho/OrthogonalViews.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraCommandLineArgs.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ScreenScalesConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ScreenScalesConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/GsonHelpers.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/ScreenScalesConfigSerializer.java

- Change screen scales from running Paintera instance
- de-/serialize from/to paintera project file
- set screen scales from geometric sequence
before merge:

Set screen scales in UI

---

src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintActions2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/RestrictPainting.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/Mask.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/Masks.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/exception/CannotPersist.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/exception/MaskedSourceException.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/persist/LabelBlockLookupUpdateNotSupported.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/persist/PersistCanvas.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/persist/UnableToPersistCanvas.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/persist/UnableToUpdateLabelBlockLookup.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/BackgroundCanvasIterable.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/BlockSpec.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/DatasetSpec.java
src/main/java/org/janelia/saalfeldlab/paintera/exception/PainteraRuntimeException.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/util/grids/Grids.java
src/main/java/org/janelia/saalfeldlab/util/math/ArrayMath.java
src/main/java/org/janelia/saalfeldlab/util/math/DoubleHasNonIntegralValue.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java
src/test/java/org/janelia/saalfeldlab/paintera/data/n5/BackgroundCanvasIterableTest.java
src/test/java/org/janelia/saalfeldlab/util/grids/GridsTest.java
src/test/java/org/janelia/saalfeldlab/util/math/ArrayMathTest.java

This is a PR to track progress of fixing the commit canvas bug.
Currently, I am stripping down the `CommitCanvasN5` class to have smaller units with unit tests and documentation. Will update once ready for a merge.
Fixes #124

Fix commit canvas

---

src/main/java/bdv/fx/viewer/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/bdv/fx/viewer/ViewerState.java
src/main/java/org/janelia/saalfeldlab/fx/ortho/OrthogonalViews.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraTestMultiChannel.java
src/main/java/org/janelia/saalfeldlab/paintera/data/RandomAccessibleIntervalDataSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/axisorder/AxisOrder.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5DataSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5DataSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5DataSourceSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/IntersectingSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/SourceStateSerialization.java
src/main/java/org/janelia/saalfeldlab/paintera/state/IntersectingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/InvertingRawSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/MinimalSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/RawSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/SourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/ThresholdingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDataset.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDatasetHandler.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/axisorder/AxisOrderPane.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/StatePane.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Data.java
src/test/java/org/janelia/saalfeldlab/paintera/state/SourceInfoTest.java

Move axis order management from source to state 
- more appropriate place
- does not interfere with source transform!
- can change axis order of sources interactively, now!

Axis order revisited

---

src/main/java/org/janelia/saalfeldlab/paintera/ui/source/SourceTabs.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/SourceStateUIElementsDefaultFactory.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/SourceStateUIElementsFactory.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/StatePane.java

Add SciJava plugin detection for source state ui configuration elements in the sidebar.
With auto-detection of openers and serializers, now entirely

Make ui elements discoverable

---

src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/FileSystem.java

N5FSWriter cannot be constructed with symlink
Fixes #157

Get real path of home directory

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java

Add options:
- `--exclude` - patterns to be excluded
- `--include` - patterns to be included
- `--only-explicitly-included` - use only datasets that were included via `--include` patterns; equivalent to `--exclude .*`

Add command line options to include/exclude data sets

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java

Check correct group for dataset attributes

Fix multi-scale channel data support in PainteraShowContainer

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraTestMultiChannel.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5ChannelDataSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5ChannelDataSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java

Currently, sources channel sources are zero extended. NaN extension is more meaningful, though.

Extend channel sources with NaN

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java

Add correct check for multiscale label data

---

src/main/java/bdv/fx/viewer/render/RenderUnit.java

Fixes #196 
@igorpisarev Please try and confirm before I merge.

Restrict RenderUnit.requestRepaint to dimensions

---

src/main/java/org/janelia/saalfeldlab/paintera/control/assignment/FragmentSegmentAssignmentOnlyLocal.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/assignments/FragmentSegmentAssignmentOnlyLocalSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/assignments/N5FragmentSegmentAssignmentInitialLutSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/ModalGoldenAngleSaturatedHighlightingARGBStream.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5FragmentSegmentAssignmentInitialLut.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java

Otherwise, initial lut cannot be loaded when reading label source from project file
Fixes #198

Serialize initial lut supplier in paintera project

---

src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java

Restrict width of the bottom status bar

---

pom.xml
src/main/java/org/janelia/saalfeldlab/util/grids/LabelBlockLookupAllBlocks.java

Label block lookup parameter target annotation

---

src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfigBase.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java

Remove orthoslice delay setting

---

pom.xml
src/main/java/bdv/fx/viewer/OverlayPane.java
src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/bdv/fx/viewer/scalebar/ScaleBarOverlayConfig.java
src/main/java/bdv/fx/viewer/scalebar/ScaleBarOverlayRenderer.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ScaleBarOverlayConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/config/ScaleBarOverlayConfigSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/fx/FontSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/Crosshair.java
src/main/java/org/janelia/saalfeldlab/util/Colors.java

Add scale bar overlay to fix #238 
Still WIP but getting there.

Scale bar overlay

---

src/main/java/org/janelia/saalfeldlab/paintera/control/OrthoViewCoordinateDisplayListener.java
src/main/java/org/janelia/saalfeldlab/paintera/control/navigation/CoordinateDisplayListener.java

Fixes #204
@aschampion Does this fix #204 for you?

Update coordinate display when navigating with keys

---

pom.xml
src/main/java/org/janelia/saalfeldlab/paintera/config/ArbitraryMeshConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/catmaid/CatmaidJsonFormat.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/catmaid/CatmaidJsonLoader.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/catmaid/CatmaidJsonWriter.java

Add support for importing CATMAID json mesh format

---

README.md

Add zenodo tag

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraCommandLineArgs.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java

Avoid creating a huge number of threads.

Make sure only one executor service is used during discovery through cli

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/Scene3DHandler.java

Fixes #307
Before I merge, please confirm that this fixes the issue for you @sheridana
One way to get this to run, is
```
git clone https://github.com/saalfeldlab/paintera
cd paintera
git checkout fix-307
mvn clean install
jgo -u org.janelia.saalfeldlab:paintera:0.19.3-SNAPSHOT:@Paintera+org.slf4j:slf4j-simple:1.7.25
```
If you run this from within a conda environment with paintera, `jgo` will be available. You can install `jgo` through conda
```
conda install -c conda-forge jgo
```
or pip
```
pip install jgo
```
otherwise.

Consider min of source interval when centering at a source

---

src/main/java/org/janelia/saalfeldlab/fx/ui/MarkdownPane.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/BookmarkConfigNode.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/BookmarkSelectionDialog.java

This PR adds markdown rendering to bookmarks for more informative bookmark texts

Bookmark node markdown

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera2.kt
src/main/java/org/janelia/saalfeldlab/paintera/PainteraMainWindow.kt

Paintera2: Open datasets specified on the CLI

---

README.md
pom.xml

Remove ?raw=true option from README.md

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera2.kt
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java

In particular for missing `maxId' attribute
Fixes #338

Improve error logging when deserialization fails

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGenerator.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java

Fixes #337
Before this commit, a listener would be added to the `isManagedProperty` of the `meshSettings` to update the `MeshGenerator` with appropriate global or individual `MeshSettings`. For some reason, this kept the internal JavaFX classes `NGMeshView` and `MeshView` alive, prohibiting clean-up of their resources, and, as a result, leaking memory. This commit fixes this issue by adding a `meshSettingsProperty` to the `MeshGenerator` that the caller can `unbind` to remove the listener that holds on to the `MeshManager`'s resources.

Release MeshGenerator resources when disposed

---

pom.xml

Fixes viewer maximization https://github.com/saalfeldlab/paintera/pull/351#issuecomment-557300181

bump to saalfx-0.1.2

---

pom.xml

Two bug-fixes:
- allow null values for object fields
- use correct string representation for extracted results in fuzzy matching

Bump saalfx version

---

src/main/java/bdv/fx/viewer/multibox/MultiBoxOverlayConfig.kt
src/main/java/bdv/fx/viewer/multibox/MultiBoxOverlayFX.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars2.kt
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers2.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/MultiBoxOverlayConfigNode.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/MultiOverlayBoxConfigNode.kt
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties2.kt

For some screenshots it is desirable to not have the overlay

Add option to disable multi-box overlay

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/meshes/managed/adaptive/AdaptiveResolutionMeshManager.kt

Fix memory leak when meshes are refreshed

---

src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java

Opening the project containing deprecated label sources didn't work and threw an exception: #407

Fix opening project with label sources in deprecated LabelSourceState format

---

src/main/java/bdv/fx/viewer/render/MultiResolutionRendererGeneric.java

Fix race conditions at startup in multi-resolution renderer

---

pom.xml
src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFillTransformedCylinder3D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/Paint2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintClickOrDrag.java

Addresses the refresh issues #420 as well ass some additional edge-case bugs found in the meantime:
- when painting at certain rotations, flood fill algorithm was not filling properly with brush depth of 1 pixel. 
- Optimized painting strategy when axis aligned was not working on views other than the top left.

Refresh fix

---

src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/test/java/org/janelia/saalfeldlab/paintera/PainteraBaseViewTest.java

closes #243
Headless test support was actually added previously with commit 2d7927d however the test reference in #243 was not added back in, until this PR

bugfix: add headless test for #243

---

src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSlicesManager.java
src/test/java/org/janelia/saalfeldlab/paintera/PainteraBaseViewTest.java
src/test/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5Test.java
src/test/kotlin/org/janelia/saalfeldlab/paintera/ui/SplashScreenTest.kt

Headless tests ran in IDE environment, but not through maven test phase. This resolves that issue.

fix: headless tests didn't run properly with release script

---

README.md
pom.xml
src/main/java/bdv/fx/viewer/render/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/render/RenderUnit.java
src/main/kotlin/bdv/fx/viewer/render/RenderUnits.kt
src/main/kotlin/bdv/fx/viewer/render/ViewerRenderUnit.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/BindingKeys.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/Paintera.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/cache/SamEmbeddingLoaderCache.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/ui/menus/PainteraMenuItems.kt

fix volatile rendering bug
bump imglib2-label-multisets
some miscellaneous style/chore

bugfix and perf

---

.github/workflows/build-installers.yml
pom.xml
src/packaging/linux/control
src/packaging/linux/jpackage.txt
src/packaging/linux/postinst
src/packaging/linux/postrm
src/packaging/osx/jpackage.txt
src/packaging/windows/jpackage.txt

postinst wasn't calling the template scripts for destkop setup; version was not incremented

fix: postinst, version
