saalfeldlab/paintera

src/main/java/org/janelia/saalfeldlab/paintera/N5Helpers.java

`N5HDF5Reader.list( String path )` throws unchecked exception if `path` is dataset. Therefore, check if `path` is a dataset before listing contents.

Do not check for multiscale if path is dataset

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraCommandLineArgs.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/config/Config.java
src/main/java/org/janelia/saalfeldlab/paintera/config/CrosshairConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/CrosshairConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/control/CurrentSourceRefreshMeshes.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Navigation.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSourceSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/InterruptibleFunction.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManager.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignment.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/cache/CacheUtils.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshPane.java

Addresses 3/5 of the bullet points in #1:
The other bullet points cannot be addressed before the imglib2-cache feature `invalidateMatching( Predicate< K > )` is implemented, therfore closes #1

Update meshes on paint

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java

- In the (private) method `MeshManagerSimple.removeMesh( MeshGenerator )`, the generator is not removed from the map. In subsequent calls to `MeshManager.addMesh`, no new mesh is added (because the entry is already present). Instead, call `MeshManagerSimple.removeMesh( N )`.
- Rename `MeshManagerSimple.removeMesh( MeshGenerator )` to `MeshManagerSimple.disable( MeshGenerator )` to reduce ambiguity
Fixes #54

Use keySet instead of values in MeshManagerSimple.removeAllMeshes

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraCommandLineArgs.java
src/main/java/org/janelia/saalfeldlab/paintera/ProjectDirectoryNotSpecified.java
src/main/java/org/janelia/saalfeldlab/paintera/ProjectDirectoryNotSpecifiedDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/TmpDirectoryCreator.java

If no project is specified on command line, show dialog with options to
1. specify proejct directory,
2. use temporary project directory, or
3. cancel (quit).
added options:
| Option | Effect |
| -------- | --- |
| `--default-to-temp-directory` | chooses (2) by default |
| `--print-error-codes` | print all Paintera error codes |

Force project directory

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/CommitDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/SaveOnExitDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/control/CommitChanges.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java

Instead of having separate keys to commit canvas and assignment (and potentially other things like annotations), use `ctrl` + `C` to pop-up dialog for user to selcet which properties to commit.
Also, pop-up dialog to commit canvas for every state with `MaskedSource` data that has uncommited canvas on exit (uncommited canvases will be lost on exit).

Commit dialog

---

README.md
src/main/java/org/janelia/saalfeldlab/fx/event/EventFX.java
src/main/java/org/janelia/saalfeldlab/fx/event/MouseClickFX.java
src/main/java/org/janelia/saalfeldlab/fx/ui/DoubleField.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/NavigationConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Navigation.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java
src/main/java/org/janelia/saalfeldlab/paintera/control/navigation/ButtonRotationSpeedConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/control/navigation/KeyRotate.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java

- add third speed level for key rotation (slow, regular, fast, defaulting to `0.5`, `5`, `45`, respectively)
- add ui controls for speed level config (in pane on right side: `settings>Navigation>Rotations>Key Rotation Speeds`)
- (de-)serialize key rotation speeds
- always consume events in `EventFX.EventFXWithConsumer.actOn`
- also allows to uncomment click painting in `Paint` handler class
Fixes #76

Set rotation speed in ui

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerSimple.java
src/main/java/org/janelia/saalfeldlab/paintera/state/IntersectingSourceState.java

Added bindings for (omitted other bindings like opacity or visibility)
- meshSimplificationIterations
- smoothingIterations
- smoothingLambda
cc @axtimwalde

Bind synapse settings to global neuron settings

---

src/main/java/org/janelia/saalfeldlab/paintera/control/ControlUtils.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Navigation.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java
src/main/java/org/janelia/saalfeldlab/paintera/control/navigation/Zoom.java

OpenJFX 11 and Oracle's JFX treat `shift scroll` as horizontal scroll, breaking zoom out and brush depth. For any scroll control, use the scroll direction that has the largest absolute value.
https://twitter.com/hanslovsky/status/1050485945940791303
https://bugs.openjdk.java.net/browse/JDK-8179102

Fix shift scroll issues

---

src/main/java/org/janelia/saalfeldlab/fx/ui/Exceptions.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintClickOrDrag.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/PainteraAlerts.java

- convenience methods for creating alerts with title `Paintera`.
- convenience method for creating exception alert with title `Paintera`
- single uniified handler for click and drag/move paint
- show dialog when submitting mask takes longer than 1s
- show dialog when committing canvas with error status if appropriate
Fixes #154 
Could help resolving #152 because we have more information about current state now.

Masked source blocks actions

---

src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/BackgroundCanvasIterable.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/converter/HighlightingStreamConverterSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/MinimalSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/HighlightingStreamConverter.java
src/main/java/org/janelia/saalfeldlab/paintera/stream/HighlightingStreamConverterIntegerType.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/SourceStateUIElementsDefaultFactory.java

This branch was initially started to make painting usable for scalar label types (i.e. not `LabelMultisetType`) by adding canvas-commit support for scalar label types (#118). Scalar label types have not been used and as such more bugs came to light while fixing this particular one. In particular, this PR
- fixes #118,
- fixes #162, and
- fixes #163

Commit canvas for scalar label types

---

src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/control/CommitChanges.java
src/main/java/org/janelia/saalfeldlab/paintera/control/CurrentSourceRefreshMeshes.java
src/main/java/org/janelia/saalfeldlab/paintera/control/IdSelector.java
src/main/java/org/janelia/saalfeldlab/paintera/control/Paint.java
src/main/java/org/janelia/saalfeldlab/paintera/control/ShowOnlySelectedInStreamToggle.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/RestrictPainting.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/SelectNextId.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/N5DataSourceDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/id/IdService.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/LabelSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasFragmentSegmentAssignments.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasHighlightingStreamConverter.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasIdService.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasLockedSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMaskForLabel.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMeshCache.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMeshes.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasSelectedIds.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/SourceInfo.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/ARGBStreamSeedSetter.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDatasetHandler.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java

When trying to open a Label dataset that has no `maxId` attribute, show dialog, with choices
1. manually enter `maxId`,
2. scan data for `maxId`, or
3. not use an `IdService` (and subsequently no painting of new label and no merge/detach actions).
This should fix #155, albeit solved a little different than proposed in the issue.

Add support for label datasets without maxId

---

src/main/java/org/janelia/saalfeldlab/fx/MenuFromHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/state/IntersectingSourceState.java

This PR fixes the build in the latest version of Eclipse Oxygen & Oracle JDK 10. The reason is likely a compiler bug because the code was certainly valid but the implicit conversions seemed to trigger false positive compiler errors.

Build fixes: Eclipse Oxygen, Oracle JDK 10

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java

Fixes #18
Most(if not all) private static methods should be moved to helper/utility class. This should happen in the future (not as part of this PR), once a good place for these methods has been established. `N5Helpers` might be a good place for this but UI elements are used as well. Maybe creating a new class would be more adequate.

Open label data in PainteraShowContainer

---

pom.xml
src/main/java/org/janelia/saalfeldlab/paintera/PainteraShowContainer.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Helpers.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Types.java
src/test/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5Test.java
src/test/java/org/janelia/saalfeldlab/util/n5/N5HelpersTest.java
src/test/java/org/janelia/saalfeldlab/util/n5/N5TestUtil.java

Fixes #183:
- Add throwing-functions dependency
- Do not use Paths.get for getting finest/coarsest datasets
Needs to

Fix windows test bug

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraCommandLineArgs.java

Currently, the --add-source command line parameters are not behaving well currently. Remove for now and re-implement, once remkop/picocli#358 is fixed. As far as I understand, this addresses "structured" options.

Remove unmaintained paintera args

---

src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/bdv/fx/viewer/render/MultiResolutionRendererFX.java
src/main/java/bdv/fx/viewer/render/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/render/RenderUnit.java
src/main/java/bdv/fx/viewer/render/TransformAwareBufferedImageOverlayRendererFX.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceFX.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceMeshFX.java

This is a revised version of #180. The difference is that the issue with scaling of border tiles here is solved differently: instead of rendering only the truncated part and keeping track of scaling coefficients, the border tiles are rendered in full, and then only the visible part is used.
Summary of changes:
- 1px padding is applied to each rendered tile on each side (the padding is always the same regardless of the screen scale used)
- Instead of using the grid layout to arrange tile images, they are now cropped (to remove the padding) and drawn onto a canvas at their corresponding grid position
- Texture coordinates for the meshes are recomputed each time the rendered tile image changes
- Border tiles are extended to be of the same size as regular tiles
- After a tile is rendered, its …

Fix interpolation artifacts between render tiles [revised]

---

src/main/java/org/janelia/saalfeldlab/util/n5/N5FragmentSegmentAssignmentInitialLut.java

Spamming users with exceptions that do not have any effect is just confusing.
Also, info seems to be a better log level here

Log exception only in DEBUG mode

---

src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/bdv/fx/viewer/ViewerState.java
src/main/java/bdv/fx/viewer/render/MultiResolutionRendererGeneric.java
src/main/java/bdv/fx/viewer/render/RenderUnit.java
src/main/java/bdv/fx/viewer/render/RenderingModeController.java
src/main/java/org/janelia/saalfeldlab/paintera/control/IdSelector.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintActions2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintClickOrDrag.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/RestrictPainting.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceFX.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceMeshFX.java

**Motivation**: multi-tile rendering (currently used rendering scheme) enables very responsive painting which is great. But, when browsing through a dataset, the tiles are rendered and updated at different times, and the picture may look inconsistent, especially during rapid zooming/translation/rotation.
This PR allows the renderer to work in two different modes: rendering the entire screen as a single image (for navigation), and rendering it as multiple tile images (for painting). This way, the picture looks consistent when browsing the data while painting is kept responsive.
------------------------------
**Changes:** The new class `RenderingModeController` switches between the modes when needed by using `renderUnit.setBlockSize()` and keeps track of some extra information.
When …

Different rendering modes for navigation/painting

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/ThresholdingSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/ThresholdingSourceStateSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/RawSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/RawSourceStateThreshold.java
src/main/java/org/janelia/saalfeldlab/paintera/state/ThresholdingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/state/SourceStateUIElementsDefaultFactory.java

Closes #212 
When raw source is active, press `ctrl-T` to open dialog for adding appropriate source.
This also gave me the idea for a more general predicate source with an arbitrary number of filters (greater, smaller, greater equal, smaller equal, equal).

Expose thresholding config through GUI and add shortcut to create threshold from RAW

---

src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill.java
src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasFloodFillState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java

* Display progress indicator during flood filling in the status bar
* Allow to cancel flood fill via context menu of the progress indicator
* Other minor fixes (ensure correct threading, react to random seed updates in the color stream)
Cancellation of a running flood-fill operation is "fake": it only resets the mask and the state, but the operation itself will continue to run in a background thread until it's completed. There is currently no way to interrupt active flood-fill operation, and this would need to be implemented in `net.imglib2.algorithm.fill.FloodFill`. For now I've put a TODO there because it would be nice to add, but it doesn't hurt (the result of the operation will be simply ignored, and the temporary mask will be garbage-collected after that).

Interactive progress indicator for flood filling

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceStateIdSelectorHandler.java

I sometimes find myself trying to toggle label ids with `Ctrl`+left click similar to how one would select multiple files, for example, in a file browser application. This PR adds this shortcut in addition to the right click for toggling.

Allow to toggle ids with Ctrl+left click

---

src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/GenericBackendDialogN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/n5/N5OpenSourceDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/meta/ChannelInformation.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/meta/MetaPanel.java

Currently, channel sources can only be added with all channels through the opener dialog; `PainteraShowContainer` can select individual channels. I added channel selection to the opener dialog to make channel data loading useful for scenarios such as affinity prediction w/long range affinities.
Fixes #172

Channel selection in opener dialog

---

src/main/java/bdv/fx/viewer/OverlayPane.java

Before this fix the crosshair overlays wouldn't get repainted when the layout changes, causing them to look inconsistent with the new layout.

Repaint crosshair overlays when layout changes

---

README.md
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceStateMergeDetachHandler.java

Adds a new shortcut `Ctrl`+`Shift`+`M` that will merge all selected fragments as described in #137.
(let me know if there are any better ideas for the key combination)
* If the last selected fragment belongs to a segment, its ID will be used for merging
* Otherwise, if the last selection doesn't belong to any assignment or is empty, the segment ID is chosen arbitrarily based on the assignment of the selected fragments (the order is not specified)
* If all selected fragments are trivial and are not part of any assignment, a new segment ID is created

Add merge all selected action (Ctrl+Enter)

---

pom.xml
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/test/java/org/janelia/saalfeldlab/paintera/PainteraBaseViewTest.java

Fixes #241 
The culprit in `LabelSourceState`:
```java
this.shapeInterpolationMode.modeStateProperty().addListener(shapeInterpolationModeStatusUpdater);
this.shapeInterpolationMode.activeSectionProperty().addListener(shapeInterpolationModeStatusUpdater);
```
If no `MaskedSource` is provided, `this.shapeInterpolationMode` is `null`. Added check for `null` for all other cases.

Fix 241 NPE in pbv.add single scale label source

---

pom.xml
src/main/java/org/janelia/saalfeldlab/fx/TitledPanes.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ArbitraryMeshConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ArbitraryMeshConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshGeneratorJobManager.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/Meshes.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/TriangleMeshFormat.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/TriangleMeshLoader.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/TriangleMeshWriter.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/obj/ObjFormat.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/obj/ObjLoader.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/obj/ObjWriter.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/ArbitraryMeshConfigSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java

I added support for loading arbitrary meshes into the Paintera viewer. @cpatrickc this will allow you to import the fafb landmark mesh into Paintera.
Example image with examples `alfa147.obj` and `al.obj` from https://people.sc.fsu.edu/~jburkardt/data/obj/obj.html:
The UI in the side bar has a new entry `Triangle Meshes` and new meshes can be added with the `+` button.
Addresses the first item of #254

Mesh openers

---

src/main/java/org/janelia/saalfeldlab/paintera/config/Viewer3DConfig.java
src/main/java/org/janelia/saalfeldlab/paintera/config/Viewer3DConfigNode.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Viewer3DConfigSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/Scene3DHandler.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/Viewer3DFX.java

Fixes #244 
Also adds a background color setting for the 3D viewer (in the future this could be extended to using a gradient).
Deserializing configurations and binding UI elements to the config is a little messy, not just for the 3D viewer, because the `Properties` object holds both config and sources. This should be addressed in a separate PR in a larger refactoring effort. It should be fairly easy to maintain backwards compatibility for existing Paintera projects.

Remember 3d viewer transform

---

src/main/java/org/janelia/saalfeldlab/paintera/control/ShapeInterpolationMode.java

Just a minor fix for this exception that appears after exiting shape interpolation mode:
```
Exception in thread "pool-3-thread-1" java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-1
at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
at org.janelia.saalfeldlab.paintera.meshes.MeshManagerWithAssignmentForSegments.removeMeshes(MeshManagerWithAssignmentForSegments.java:245)
at org.janelia.saalfeldlab.paintera.meshes.MeshManagerWithAssignmentForSegments.update(MeshManagerWithAssignmentForSegments.java:159 …
```

Fix threading in shape interpolation mode

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java

Fixes #283
[`root.getChildren().setAll`](https://github.com/saalfeldlab/paintera/blob/master/src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshManagerWithAssignmentForSegments.java#L245) would remove all meshes that are not managed by the mesh manager. To solve this, add a separate group that is guaranteed to hold only meshes of the mesh manager.
Let me know what you think @igorpisarev

Add additional group to MeshManagerWithAssignmentForSegments

---

.travis.yml

See also: https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/8

Specify dist: trusty to move back to Trusty images

---

src/main/java/bdv/fx/viewer/ViewerPanelFX.java
src/main/java/bdv/fx/viewer/ViewerState.java
src/main/java/bdv/fx/viewer/multibox/MultiBoxOverlayRendererFX.java
src/main/java/bdv/fx/viewer/render/RenderUnit.java
src/main/java/org/janelia/saalfeldlab/paintera/control/ShapeInterpolationMode.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/FloodFill2D.java
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/RestrictPainting.java

Closes #239 
The cause for the deadlock was that the list of sources in `ViewerState` was modified under the lock, and since it was an `ObservableList`, it immediately notified the listeners about the change while still holding the lock.
I've changed it to a regular list and `ViewerState` to implement `Observable` instead. It will fire the invalidated event after releasing the lock which eliminates the risk of running into a deadlock.
For consistency it will also fire when the viewer transform or the timepoint changes. I also slightly changed types and visibility of the class members in `ViewerState` to make it more straightforward.

Fix deadlock at startup

---

create-changelog.kts

[UNVERSIONED] Auto-generate release note by @hanslovsky 
Add a [kscript](https://github.com/holgerbrandl/kscript) that auto-generates release notes from pull request messages:
1. Scan commits from current `HEAD` to tag with latest version smaller than current (SNAPSHOT) version.
2. Filter all commit messages
3. In each commit message, look for any of these tags, encapuslated in brackets `[$TAG]`:
- `BREAKING`
- `FEATURE`
- `BUGFIX`
- `UNVERSIONED`
The script will suggest a new SemVer version based on the presence of these tags (`UNVERSIONED` will not increase the version). For example, if `HEAD` was on 8018669, the output would be:
```
$ ./create-changelog.kts
Previous release: 0.18.0
- Merge pull request #290 from uschmidt83/patch-1: Typo in Readme
Merge pull request #290 from …
```

Auto-generate release note

---

src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/IntersectingSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/intersecting/IntersectingSourceStateOpener.java

Confirmed with @cpatrickc that this works: Through the opener menu dialog add an intersecting source state from an already existing label source state and thresholded source state.
Fixes #295

Intersecting source state dialog

---

src/main/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/dialogs/create/CreateDataset.java
src/main/java/org/janelia/saalfeldlab/util/n5/N5Data.java

Closes #297 
It seems that I did a pretty shallow search for usages of label multisets when doing #281, so the only affected place is persisting the canvas, which will now ensure that the attribute "isLabelMultiset" is set for downscaled datasets.
The code still uses the old way of reading label multiset data when opening the project, and it's using a global cache for that, which is not currently exposed via `N5LabelMultisets`. Changing the attributes would also be quite hacky there because we need an `N5Writer` for that, and the rest of the opener code assumes `N5Reader`. I added a TODO there and suggest to keep it for now as it is.

Fix "not a label multiset" error

---

src/main/java/org/janelia/saalfeldlab/paintera/data/n5/BackgroundCanvasIterable.java
src/main/java/org/janelia/saalfeldlab/paintera/data/n5/CommitCanvasN5.java
src/test/java/org/janelia/saalfeldlab/paintera/data/n5/BackgroundCanvasIterableTest.java

Fixes #294
We currently have special values
```
TRANSPARENT = -0x1L // -1L or uint64.MAX_VALUE
INVALID = -0x2L // -2L or uint64.MAX_VALUE - 1
OUTSIDE = -0x3L // -3L or uint64.MAX_VALUE - 2
MAX_ID = -0x4L // -4L or uint64.MAX_VALUE - 3
```
@axtimwalde @igorpisarev do you see any use case where we should actually paint a special value? In that case, this check would be to aggressive.

Exclude all special value labels when committing canvas

---

README.md
pom.xml
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars2.kt
src/main/java/org/janelia/saalfeldlab/paintera/Paintera.java
src/main/java/org/janelia/saalfeldlab/paintera/Paintera2.kt
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers.java
src/main/java/org/janelia/saalfeldlab/paintera/PainteraDefaultHandlers2.kt
src/main/java/org/janelia/saalfeldlab/paintera/PainteraGateway.kt
src/main/java/org/janelia/saalfeldlab/paintera/PainteraMainWindow.kt
src/main/java/org/janelia/saalfeldlab/paintera/SaveOnExitDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/config/ArbitraryMeshConfigNode.kt
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/TriangleMeshFormat.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/io/TriangleMeshFormatService.kt
src/main/java/org/janelia/saalfeldlab/paintera/serialization/GsonHelpers.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/PainteraSerialization.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/StatefulSerializer.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/menu/OpenDialogMenu.java
src/main/java/org/janelia/saalfeldlab/util/SciJavaUtils.java

This adds a REPL that can be opened via the menu (`View>Show REPL`) or via `Ctrl+Alt+T`.
In order to re-use context, I added a new `PainteraGateway` to include all relevant services.
Fixes #138

Add SciJava repl

---

pom.xml

Addresses plugin detection: Add `src/main/java` to sources for kotlin annotator processing.
@igorpisarev If you re-visit the Windows issues, please use this branch.

Add src/main/java to kapt

---

src/main/java/org/janelia/saalfeldlab/paintera/control/paint/PaintActions2D.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceStatePaintHandler.java
src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceStatePreferencePaneNode.kt

Fixes #354
I removed the upper bound for the brush radius completely but it may make sense to actually have an upper bound, e.g. the longest diagonal of the dataset in world space.

Always change brush radius by multiplication and remove upper bound for brush radius

---

README.md

`paintera-conversion-helper` was deprecated, but is still described in the README.

Replace paintera-conversion-helper with paintera-convert in README

---

pom.xml

This will hopefully skip the javadoc also in the deploy-to-scijava profile

[BUGFIX] add <javadoc.skip> property

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/n5/N5Backend.kt

Previously, the !N5Helpers.isMultiScale was checked when creating a multi-scale backend, resulting in single-scale datasets being created as multi-scale (which worked but was wrong). Thanks @igorpisarev for finding and reporting this bug.

Use correct condition in Label N5Backend

---

src/main/java/org/janelia/saalfeldlab/paintera/state/LabelSourceStateIdSelectorHandler.java

'Select all' is broken in most recent master because of the incorrect key binding.

Fix key binding for 'select all' action

---

src/main/java/org/janelia/saalfeldlab/paintera/config/BookmarkConfigNode.kt

When the bookmark note is `null` in the deserialized project configuration, the following exception was printed:
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Optional.ofNullable(book…"\n", " ") }.orElse(null) must not be null
at org.janelia.saalfeldlab.paintera.config.BookmarkConfigNode$BookmarkTitledPane.<init>(BookmarkConfigNode.kt:122)
at org.janelia.saalfeldlab.paintera.config.BookmarkConfigNode.updateChildren(BookmarkConfigNode.kt:153)
at org.janelia.saalfeldlab.paintera.config.BookmarkConfigNode.access$updateChildren(BookmarkConfigNode.kt:29)
at org.janelia.saalfeldlab.paintera.config.BookmarkConfigNode$configListener$1.changed(BookmarkConfigNode.kt:55)
at org.janelia.saalfeldlab.paintera.config.BookmarkConfigNode$configListener$1.changed(Bookm …
```

Fix creating bookmark node after deserialization when its note is null

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/ConnectomicsLabelBackend.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/ConnectomicsLabelState.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/LabelSourceStateFallbackDeserializer.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/n5/N5BackendMultiScaleGroup.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/n5/N5BackendPainteraDataset.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/n5/N5BackendSingleScaleDataset.kt

So far, there is no reason to provide locked segments via the backend but it may happen in the future.
@cpatrickc noticed that locked segments did not appear locked when converting deprecated datasets. This commit addresses this issue.

Move locked segments into state rather than backend [BUGFIX]

---

src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars2.kt
src/main/java/org/janelia/saalfeldlab/paintera/control/paint/SelectNextId.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasFloodFillState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasFragmentSegmentAssignments.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasHighlightingStreamConverter.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasIdService.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasLockedSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMaskForLabel.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMeshCache.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasMeshes.java
src/main/java/org/janelia/saalfeldlab/paintera/state/HasSelectedIds.java
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/ConnectomicsLabelState.kt

Fixes #370
Progress indication and cancellation of 3D flood-fill didn't work because `ConnectomicsLabelState` didn't implement `HasFloodFillState`. I added an implementation of this interface and also implemented the rest of the 'marker' interfaces similar to how it's done in `LabelSourceState` (such as `HasMeshes`, `HasSelectedIds`, and so on). I'm not quite sure where and if it's actually used, but some of these interfaces are a bit superfluous, and perhaps they can be removed or merged into one less granular interface.

Fix display status of ConnectomicsLabelState

---

create-changelog.kts

This is necessary becayse `http://jcenter.bintray.com` would be used instead and jcenter.bintray fails with 403 instead of redirecting to https

Explicitly add https repo for jcenter.bintray in changelog creation script

---

src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.java
src/main/java/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars2.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfig.kt
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfigBase.java
src/main/java/org/janelia/saalfeldlab/paintera/config/OrthoSliceConfigNode.kt
src/main/java/org/janelia/saalfeldlab/paintera/serialization/Properties.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/Geom3DUtils.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceFX.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceMeshFX.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSlicesManager.java
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/ViewFrustumCulling.java

Adds new slider in OrthoViews settings for controlling transparency of the orthoslices.
Changing the opacity property of `MeshView` didn't have any effect on transparency (only hid the orthoslices when set to 0, otherwise fully opaque), but changing the opacity of the diffuse color in `PhongMaterial` did the trick.

Orthoslices transparency

---

src/main/java/org/janelia/saalfeldlab/paintera/meshes/cache/SegmentMaskGenerators.java

I had set them to LOG.info so could see what's happening during development but I had forgotten to re-set them to LOG.info later on.
@igorpisarev I will cut a new release right after merging this PR. I had forgotten to re-set the log levels to DEBUG and I just noticed after the release of `0.23.0`.

Set appropriate log levels in SegmentMaskGenerators

---

src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceFX.java

Fixes #395
The changes improve the performance quite a lot on my workstation and my laptop:
* Instead of changing brightness factor and alpha of the texture images on per-pixel basis using JavaFX API, it's now set directly into the buffer of the image (using `BufferExposingWritableImage` similarly to the renderer). Individual pixel updates were too slow because on each update JavaFX notified the listeners that the image has changed.
* These updates are now throttled, so the actual textures will be modified every 50ms.
* For painting, keep track of the affected intervals and update the texture only within that interval.
There is also another version of the fix that performs texture updates on a background thread: https://github.com/saalfeldlab/paintera/tree/optimize-orthoslice-textures-back …

Optimize orthoslice texture updates

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/Paintera.kt

Addresses #405. If an error occurs while trying to open a project, its stack trace will be displayed in the pop-up window.

Show stack trace if an error occurs while trying to open a project

---

src/main/java/org/janelia/saalfeldlab/paintera/control/selection/FragmentsInSelectedSegments.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshExporter.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshExporterBinary.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshExporterObj.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/MeshInfo.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/SegmentMeshInfo.java
src/main/java/org/janelia/saalfeldlab/paintera/meshes/SegmentMeshInfos.java
src/main/java/org/janelia/saalfeldlab/paintera/serialization/sourcestate/ThresholdingSourceStateDeserializer.java
src/main/java/org/janelia/saalfeldlab/paintera/state/IntersectingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/state/ThresholdingSourceState.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshExportResult.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/MeshExporterDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/SegmentMeshExportResult.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/SegmentMeshExporterDialog.java
src/main/java/org/janelia/saalfeldlab/paintera/ui/source/mesh/SegmentMeshInfoNode.java
src/main/kotlin/org/janelia/saalfeldlab/paintera/meshes/managed/MeshManagerWithSingleMesh.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/IntersectingSourceStatePreferencePaneNode.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/LabelSourceStateMeshPaneNode.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/LabelSourceStatePreferencePaneNode.kt

Adds new `Export` button under the `Meshes` tab in the menu of an intersecting source.
After selecting the output directory, the meshes will be stored in a file `synapses{segment_ids}.obj` (or `.bin`), so that the filename will include the current selection of segments that generate the synapse meshes of the intersecting source.

Add ability to export meshes for intersecting sources (synapses)

---

src/main/java/org/janelia/saalfeldlab/paintera/PainteraBaseView.java
src/main/java/org/janelia/saalfeldlab/paintera/control/actions/MenuActionType.java
src/main/kotlin/org/janelia/saalfeldlab/paintera/BorderPaneWithStatusBars.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/PainteraMainWindow.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/LabelSourceStateCommitHandler.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/state/label/CommitHandler.kt

The recently changed code didn't account for which UI actions are allowed and which aren't while in the shape interpolation mode.

Fix UI while in shape interpolation mode

---

src/main/java/org/janelia/saalfeldlab/paintera/control/ShapeInterpolationMode.java
src/main/java/org/janelia/saalfeldlab/paintera/control/actions/AllowedActionsProperty.java

To avoid redundant pop-ups, actions are disabled when generating a new label mask, and re-enabled after.
However, shape interpolation creates masks during interpolation mode. This introduced the following bug where shape-interpolation was not possible:
1. Shape interpolation mode is entered on pressing `s`. As a result, a listener is added to the `allowedActionsProperty` that checks if the allowed actions are changed, and if so exits shape interpolation mode.
2. Upon selecting a label, a mask is generated to show which label was selected
3. generating a mask triggers the `allowedActionsProperty.disable()`
4. `disable()` remove the current set of allowed actions and replaces them with an empty set (i.e. no actions are allowed).
5. Since we modified the `allowedActionsProperty`'s contents, …

don't exit shape interpolation mode if it's due to disable/enable of AllowedActions

---

pom.xml

This n5-imglib2 bump solves an issue where certain hd5f files where not having their offset metadata parsed properly.

bump n5-imglib2 version to fix hdf5 offset parsing bug

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/control/modes/NavigationControlMode.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/modes/PaintLabelMode.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/modes/ShapeInterpolationMode.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/tools/Tool.kt

A bug was discovered where right-click and drag to erase would also cause the orthoslice to translate in the xy plane, as if you where not in Paint Mode. This was caused when the Viewer lost focus (from clicking off Paintera, or minimizing) during Shape Interpolation Mode. When this occurred, the active viewer was `null` and so the navigation actions would not be removed from the previous viewer, and would persist when the window was maximized again. 
The solution changes the `LazyForeignValue` which only contains a single item, to a `LazyForeignMap` which retains the ActionSets from the previous Viewer, even when it is no longer active. This means when we do finally remove the ActionSets, they are the same instances we installed initially, not a new copy.

fix: stop translation from occurring during erase

---

src/main/kotlin/org/janelia/saalfeldlab/paintera/config/SideBarConfig.kt

Sidebar menu is now visible by default. Reopening saved paintera projects will remember configuration from last user settings.

feat: Make sidebar menu visible by default

---

.github/workflows/maven-build-all-installer.yml
pom.xml
src/packaging/linux/jpackage.txt
src/packaging/osx/jpackage.txt
src/packaging/windows/jpackage.txt

add matrix.os based installer destination to differentiate dmg files from intel vs amd mac

ci: installed destination based on matrix.os in github actions

---

README.md

I believe the "Running Paintera" subsection needs to go under "Running from source", not "Development Releases".

Move Running Paintera section in README

---

pom.xml
src/main/java/org/janelia/saalfeldlab/paintera/viewer3d/OrthoSliceMeshFX.java

some underlying platform issue with Apple Metal on M1 Mac Sonoma requires specular color to be specified for correct rendering of phong material meshes see: https://forums.macrumors.com/threads/javafx-mesh-lighting-rendering-errors-macos-14-2-1.2415934/

fix: issus with orthoslice meshes on m1 mac sonoma

---

pom.xml
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/ShapeInterpolationController.kt
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/modes/ShapeInterpolationMode.kt

bug fixes:
1. correctly invalidate eager SAM prediction slice when updating adjacent slices bounding boxes in shape interpolation
2. fix handling of empty slices in shape interpolation (empty slices are slices with no valid ID, or an empty bounding box)
3. better handling of rapid slice navigation in shape interpolation

1.10.3 shape interpolation bug fixes

---

pom.xml
src/main/kotlin/org/janelia/saalfeldlab/paintera/control/modes/ShapeInterpolationMode.kt

avoid accidentally consuming all key events when trying to filter out erroneous slice navigation events

fix ESC to exit nested tool in ShapeInterpolation
